language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --dev
